name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
 
    - name: Build with Gradle
      run: ./gradlew build

      
    - name: Upload Release APK  
      uses: actions/upload-artifact@v3
      with:
           name: TMOe release
           path: ./app/build/outputs/apk/release
